# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963b297b38dc45d17ee53c50b2de6e8ceb0682547c97bec8ef625cdaac4153da8a9d58283afc5e3409242d75adb1f19a9af8c408d0124250babb79f9e00b765e

test:
  secret_key_base: dea3943c2978f7dd0d2d6a07de15e57693c142211c4d53c39264e8e034839cd63f546ac3b62da429764565cc30fbfb1ba7650b79f9c1ddea8c83214a4d83d9dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
